name = "macoin-jbc-api"
main = "index.js"
compatibility_date = "2024-01-01"

# D1 Database Configuration
[[d1_databases]]
binding = "DB" # Must match env.DB in code
database_name = "macoin-jbc-db"
database_id = "70f8721b-5504-4c82-82be-a9e2846359b2" # Run 'wrangler d1 create macoin-jbc-db' to get this

[vars]
# Your Admin Wallet Address (Must match the one used in frontend)
ADMIN_ADDRESS = "0x4C10831CBcF9884ba72051b5287b6c87E4F74A48"
